### ISSUE TITLE
Local Hash Server Issue:  exceptoin in calling external gRoot server

### ISSUE THREAD

**Issue by dimpol** [K2/HashServer#2]
Hi @K2 

I have spawned a local hash server successfully, and then executed the following (using the appropriate credentials)

Test-AllVirtualMemory -TargetHost 192.168.2.4 -aUserName 'user' -aPassWord 'pass' -MaxThreads 256 -ElevatePastAdmin -GUIObject

Test-AllVirtualMemory has the following configuration.
$gRoot = "https://pdb2json.azurewebsites.net/api/PageHash/x"
$HashServerUri = "http://192.168.2.100:3342/api/PageHash/x <-- where hash server is running

The result was the following (on the spawned hash server): <----Any ideas?

Should I replace Program.Settings.External with Program.Settings.Internal and also replace https://pdb2json.azurewebsites.net/api/PageHash/x with my local hash server?

-----------------------

warn: Default[0]
      exceptoin in calling external gRoot server.  System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification

**Comment by K2** [comment]
Did you get this one fixed? I just committed some doc's thanks for prompting me to fill them out a bit better.  Check out https://k2.github.io/HashServer/docs/Index.html for the rendered markdown of the docs folder.  I'll publish a release soon for anybody else who's interested but not as able as you are to build and figure this stuff out alone.  Thanks again.

**Comment by dimpol** [comment]
@K2 Thank you actually, your approach is a valuable detection tool. 
Yes sorted it out this one. 

The only current unclear part is what test-allvirtualmemory scans... every time i run it i receive different results and i never see for example explorer.exe in any of the results......

**Comment by K2** [comment]
Since we only scan working set pages you can have a tremendous variability, especially since I attempt to only scan shared pages one time, this is what effect's the look of the returned validation the most.  Each time PowerShell comes in to deploy, the state of the system will be different, since most pages are shared, if I pick up portions of ntdll in process 100 this time, next time if I gather that data from process 88, when I enumerate 100.  I think it could always be improved though...

**Comment by dimpol** [comment]
I have seen very interesting results so far. Thanks again for the time spent to explain things...

**Comment by K2** [comment]
No problem.  If you use volatility you can cross verify (at least results for registered modules) with the inVtero plugin there if you do a memory dump on a host.  If you get a lot of unknown code, please let me know, at least right now the plan(I hope to get some time off to do it on the holidays, I'll put in the readme soon also), is to resolve JavaScript & .NET JIT hosts.  Since you're a PowerShell user, you will see some unverifiable code regions since you're going to have a lot of .NET JIT going on.  This can be accommodated if you get access to the pre-jitted modules into the HS.  There are some edge cases here that I'm working on and after the JavaScript JIT stuff is in, there should be virtually 100% verifiable code possible, for user space.   The kernel is mostly good on 2016 & Win10 except for the large page allocated regions for HAL and NTOS where the kernel locates some data into the +X memory for performance reasons, unfortunately since it's data, it does change quite a bit. There are some possible future plans to contain it but I'm not sure how good we can do there.
